import { Component,Pipe, PipeTransform, Injectable } from '@angular/core';

@Component({
  selector: 'app-pipes',
  standalone: false,
  templateUrl: './pipes.html',
  styleUrl: './pipes.css'
})
export class Pipes { }

@Pipe({
  name: 'propercase',
  standalone: true 
})
export class ProperCasePipe implements PipeTransform {
  transform(value: string): string {
    if (!value) return '';
    
    // Normalize spaces: remove extra spaces
    value = value.replace(/\s+/g, ' ').trim();

    // Capitalize first letter of each word
    return value
      .split(' ')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join(' ');
  }
}

@Pipe({
  name: 'tipforsource',
  standalone: true 
})
export class TipForSourcePipe implements PipeTransform {
 
  sourceTips: Record<string, string> = {
 
"CoS" : "Curse of Strahd",
"DMG" : "Dungeon Master's Guide",
"EEPC" : "Elemental Evil Player's Companion",
"EET" : "Elemental Evil: Trinkets",
"HotDQ" : "Hoard of the Dragon Queen",
"LMoP" : "Lost Mine of Phandelver",
"MM" : "Monster Manual",
"OotA" : "Out of the Abyss",
"PHB" : "Player's Handbook",
"PotA" : "Princes of the Apocalypse",
"RoT" : "The Rise of Tiamat",
"RoTOS" : "The Rise of Tiamat Online Supplement",
"SCAG" : "Sword Coast Adventurer's Guide",
"SKT" : "Storm King's Thunder",
"ToA" : "Tomb of Annihilation",
"TLK" : "The Lost Kenku",
"ToD" : "Tyranny of Dragons",
"TTP" : "The Tortle Package",
"TYP_AtG" : "Against the Giants",
"TYP_DiT" : "Dead in Thay",
"TYP_TFoF" : "The Forge of Fury",
"TYP_THSoT" : "The Hidden Shrine of Tamoachan",
"TYP_TSC" : "The Sunless Citadel",
"TYP_ToH" : "Tomb of Horrors",
"TYP_WPM" : "White Plume Mountain",
"VGM" : "Volo's Guide to Monsters",
"XGE" : "Xanathar's Guide to Everything",
"OGA" : "One Grung Above",
"MTF" : "Mordenkainen's Tome of Foes",
"WDH" : "Waterdeep: Dragon Heist",
"WDMM" : "Waterdeep: Dungeon of the Mad Mage",
"GGR" : "Guildmasters' Guide to Ravnica",
"KKW" : "Krenko's Way",
"LLK" : "Lost Laboratory of Kwalish",
"AZfyT" : "A Zib for your Thoughts",
"GoS" : "Ghosts of Saltmarsh",
"AI" : "Acquisitions Incorporated",
"OoW" : "The Orrery of the Wanderer",
"ESK" : "Essentials Kit",
"DIP" : "Dragon of Icespire Peak",
"HftT" : "Hunt for the Thessalhydra",
"DC" : "Divine Contention",
"SLW" : "Storm Lord's Wrath",
"SDW" : "Sleeping Dragon's Wake",
"BGDIA" : "Baldur's Gate: Descent Into Avernus",
"LR" : "Locathah Rising",
"AL" : "Adventurers' League",
"SAC" : "Sage Advice Compendium",
"ERLW" : "Eberron: Rising from the Last War",
"EFR" : "Eberron: Forgotten Relics",
"RMBRE" : "The Lost Dungeon of Rickedness: Big Rick Energy",
"RMR" : "Dungeons & Dragons vs. Rick and Morty: Basic Rules",
"MFF" : "Mordenkainen's Fiendish Folio",
"AWM" : "Adventure with Muk",
"IMR" : "Infernal Machine Rebuild",
"SADS" : "Sapphire Anniversary Dice Set",
"EGW" : "Explorer's Guide to Wildemount",
"EGW_ToR" : "Tide of Retribution",
"EGW_DD" : "Dangerous Designs",
"EGW_FS" : "Frozen Sick",
"EGW_US" : "Unwelcome Spirits",
"MOT" : "Mythic Odysseys of Theros",
"IDRotF" : "Icewind Dale: Rime of the Frostmaiden",
"TCE" : "Tasha's Cauldron of Everything",
"VRGR" : "Van Richten's Guide to Ravenloft",
"HoL" : "The House of Lament",
"RtG" : "Return to Glory",
"ISF" : "In Scarlet Flames",
"THP" : "The Hidden Page",
"AVT" : "A Verdant Tomb",
"AitFR_DN" : "Deepest Night",
"AitFR_FCD" : "From Cyan Depths",
"WBtW" : "The Wild Beyond the Witchlight",
"DoD" : "Domains of Delight",
"MaBJoV" : "Minsc and Boo's Journal of Villainy",
"FTD" : "Fizban's Treasury of Dragons",
"SCC" : "Strixhaven: A Curriculum of Chaos",
"SCC_CK" : "Campus Kerfuffle",
"SCC_HfMT" : "Hunt for Mage Tower",
"SCC_TMM" : "The Magister's Masquerade",
"SCC_ARiR" : "A Reckoning in Ruins",
"MPMM" : "Mordenkainen Presents: Monsters of the Multiverse",
"CRCotN" : "Critical Role: Call of the Netherdeep",
"JttRC" : "Journeys through the Radiant Citadel",
"SAiS" : "Spelljammer: Adventures in Space",
"AAG" : "Astral Adventurer's Guide",
"BAM" : "Boo's Astral Menagerie",
"LoX" : "Light of Xaryxis",
"DoSI" : "Dragons of Stormwreck Isle",
"DSotDQ" : "Dragonlance: Shadow of the Dragon Queen",
"KftGV" : "Keys from the Golden Vault",
"SCREEN" : "Dungeon Master's Screen",
"SCREEN_WILDERNESS_KIT" : "Dungeon Master's Screen: Wilderness Kit",
"SCREEN_DUNGEON_KIT" : "Dungeon Master's Screen: Dungeon Kit",
"SCREEN_SPELLJAMMER" : "Dungeon Master's Screen: Spelljammer",
"HEROES_FEAST" : "Heroes' Feast",
"CM" : "Candlekeep Mysteries",
"NRH_TCMC" :  "The Candy Mountain Caper",
"NRH_AVitW" :  "A Voice in the Wilderness",
"NRH_ASS" :  "A Sticky Situation",
"NRH_CoI" :  "Circus of Illusions",
"NRH_TLT" :  "The Lost Tomb",
"NRH_AWoL" :  "A Web of Lies",
"NRH_AT" :  "Adventure Together",
"MGELFT" : "Muk's Guide To Everything He Learned From Tasha",
"VD" : "Vecna Dossier",
"SjA" : "Spelljammer Academy",
"HAT_TG" : "Honor Among Thieves: Thieves' Gallery",
"HAT_LMI" : "Honor Among Thieves: Legendary Magic Items",
"ALCoS" : "Curse of Strahd",
"ALEE" : "Elemental Evil",
"ALRoD" : "Rage of Demons",
"PSA" : "Amonkhet",
"PSI" : "Innistrad",
"PSK" : "Kaladesh",
"PSZ" : "Zendikar",
"PSX" : "Ixalan",
"PSD" : "Dominaria",
"XMtS" : "X Marks the Spot",
"UAA" : "Artificer",
"UAEAG" : "Eladrin and Gith",
"UAEBB" : "Eberron",
"UAFFR" : "Feats for Races",
"UAFFS" : "Feats for Skills",
"UAFO" : "Fiendish Options",
"UAFT" : "Feats",
"UAGH" : "Gothic Heroes",
"UAMDM" : "Modern Magic",
"UASSP" : "Starter Spells",
"UATMC" : "The Mystic Class",
"UATOBM" : "That Old Black Magic",
"UATRR" : "The Ranger, Revised",
"UAWA" : "Waterborne Adventures",
"UAVR" : "Variant Rules",
"UALDR" : "Light, Dark, Underdark!",
"UARAR" : "Ranger and Rogue",
"UAATOSC" : "A Trio of Subclasses",
"UABPP" : "Barbarian Primal Paths",
"UARSC" : "Revised Subclasses",
"UAKOO" : "Kits of Old",
"UABBC" : "Bard: Bard Colleges",
"UACD" : "Cleric: Divine Domains",
"UAD" : "Druid",
"UARCO" : "Revised Class Options",
"UAF" : "Fighter",
"UAM" : "Monk",
"UAP" : "Paladin",
"UAMC" : "Modifying Classes",
"UAS" : "Sorcerer",
"UAWAW" : "Warlock and Wizard",
"UATF" : "The Faithful",
"UAWR" : "Wizard Revisited",
"UAESR" : "Elf Subraces",
"UAMAC" : "Mass Combat",
"UA3PE" : "Three-Pillar Experience",
"UAGHI" : "Greyhawk Initiative",
"UATSC" : "Three Subclasses",
"UAOD" : "Order Domain",
"UACAM" : "Centaurs and Minotaurs",
"UAGSS" : "Giant Soul Sorcerer",
"UARoE" : "Races of Eberron",
"UARoR" : "Races of Ravnica",
"UAWGE" : "Wayfinder's Guide to Eberron",
"UAOSS" : "Of Ships and the Sea",
"UASIK" : "Sidekicks",
"UAAR" : "Artificer Revisited",
"UABAM" : "Barbarian and Monk",
"UASAW" : "Sorcerer and Warlock",
"UABAP" : "Bard and Paladin",
"UACDW" : "Cleric, Druid, and Wizard",
"UAFRR" : "Fighter, Ranger, and Rogue",
"UACFV" : "Class Feature Variants",
"UAFRW" : "Fighter, Rogue, and Wizard",
"UAPCRM" : "Prestige Classes and Rune Magic",
"UAR" : "Ranger",
"UA2020SC1" : "2020 Subclasses, Part 1",
"UA2020SC2" : "2020 Subclasses, Part 2",
"UA2020SC3" : "2020 Subclasses, Part 3",
"UA2020SC4" : "2020 Subclasses, Part 4",
"UA2020SC5" : "2020 Subclasses, Part 5",
"UA2020SMT" : "2020 Spells and Magic Tattoos",
"UA2020POR" : "2020 Psionic Options Revisited",
"UA2020SCR" : "2020 Subclasses Revisited",
"UA2020SpellsAndMagicTattoos": "Unearthed Arcana 2020 - Spells and Magic Tattoos",
"UA2020F" : "2020 Feats",
"UA2021GL" : "2021 Gothic Lineages",
"UA2021FF" : "2021 Folk of the Feywild",
"UA2021DO" : "2021 Draconic Options",
"UA2021MoS" : "2021 Mages of Strixhaven",
"UA2021TotM" : "2021 Travelers of the Multiverse",
"UA2022HoK" : "2022 Heroes of Krynn",
"UA2022HoKR" : "2022 Heroes of Krynn Revisited",
"UA2022GO" : "2022 Giant Options",
"UA2022WotM" : "2022 Wonders of the Multiverse",
"MCV1SC" : "Spelljammer Creatures",
"MCV2DC" : "Dragonlance Creatures",
"MCV3MC" :  "Minecraft Creatures",
  "PHB'14": "Player's Handbook 2014",
    "ToR": "Tyranny of Dragons",
    "PHB'24": "Player's Handbook 2024",
    "DMG'24": "Dungeon Master's Guide 2024",
    "QftIS": "Quests from the Infinite Staircase",
    "SatO": "Sigil and the Outlands",
    "BGG": "Bigby Presents: Glory of the Giants",
    "DMG'14": "Dungeon Master's Guide 2014",
    "BMT": "Book of Many Things",
    "VEoR": "Vecna: Eve of Ruin",
    "DitLCoT": "Descent into the Lost Caverns of Tsojcanth",
    "LmoP": "Lost Mine of Phandelver",
    "MM'14": "Monster Manual (2014)",
    "MM'25": "Monster Manual (2025)",
    "PaBTSO": "Phandelver and Below: The Shattered Obelisk",
    "TftYP": "Tales from the Yawning Portal",
  };

  transform(source: string): string {
       return this.sourceTips[source] ?? source ?? "Unknown Source";
  }
}

@Pipe({
  name: 'tipfortype',
  standalone: true 
})
@Injectable({ providedIn: 'root' })
export class TipForTypePipe implements PipeTransform {
  
 
  typeTips: Record<string, string> = {
    "A": "ammunition",
	"AF": "ammunition",
	"AT": "artisan's tools",
	"EM": "eldritch machine",
	"EXP": "explosive",
	"FD": "food and drink",
	"G": "adventuring gear",
	"GS": "gaming set",
	"HA": "heavy armor",
	"INS": "instrument",
	"LA": "light armor",
	"M": "melee weapon",
	"MA": "medium armor",
	"MNT": "mount",
	"MR": "master rune",
	"GV": "generic variant",
	"P": "potion",
	"R": "ranged weapon",
	"RD": "rod",
	"RG": "ring",
	"S": "shield",
	"SC": "scroll",
	"SCF": "spellcasting focus",
	"OTH": "other",
	"T": "tools",
	"TAH": "tack and harness",
	"TG": "trade good",
	"$": "treasure",
	"VEH": "vehicle (land)",
	"SHP": "vehicle (water)",
	"AIR": "vehicle (air)",
	"SPC": "vehicle (space)",
	"WD": "wand",
};

  transform(source: string): string {
       return this.typeTips[source] ?? source ?? "Wondrous Item";
    
}

}


